# Generated by Django 4.2.10 on 2024-02-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('guid', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('aircraft_class', models.IntegerField()),
                ('power', models.IntegerField()),
                ('active', models.BooleanField()),
                ('complex', models.BooleanField()),
                ('high_perf', models.BooleanField()),
            ],
        ),
    ]
